# packages in environment at /Users/taddbindas/miniconda3/envs/lgar:
#
# Name                    Version                   Build  Channel
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
black                     23.3.0                   pypi_0    pypi
blas                      1.0                    openblas  
bmipy                     2.0                      pypi_0    pypi
bottleneck                1.3.5           py310h96f19d2_0  
brotlipy                  0.7.0           py310h1a28f6b_1002  
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2023.05.30           hca03da5_0  
certifi                   2023.5.7        py310hca03da5_0  
cffi                      1.15.1          py310h80987f9_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.3                    pypi_0    pypi
cryptography              39.0.1          py310h834c97f_2  
filelock                  3.9.0           py310hca03da5_0  
freetype                  2.12.1               h1192e45_0  
giflib                    5.2.1                h80987f9_3  
gmp                       6.2.1                hc377ac9_3  
gmpy2                     2.1.2           py310h8c48613_0  
hydra-core                1.3.2                    pypi_0    pypi
idna                      3.4             py310hca03da5_0  
jinja2                    3.1.2           py310hca03da5_0  
jpeg                      9e                   h80987f9_1  
lcms2                     2.12                 hba8e193_0  
lerc                      3.0                  hc377ac9_0  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.17                 h80987f9_0  
libffi                    3.4.4                hca03da5_0  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libtiff                   4.5.0                h313beb8_2  
libwebp                   1.2.4                ha3663a8_1  
libwebp-base              1.2.4                h80987f9_1  
llvm-openmp               14.0.6               hc6e5704_0  
lz4-c                     1.9.4                h313beb8_0  
markupsafe                2.1.1           py310h1a28f6b_0  
mpc                       1.1.0                h8c48613_1  
mpfr                      4.0.2                h695f6f0_1  
mpmath                    1.2.1                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
mypy_extensions           0.4.3           py310hca03da5_1  
ncurses                   6.4                  h313beb8_0  
networkx                  2.8.4           py310hca03da5_1  
numexpr                   2.8.4           py310hecc3335_1  
numpy                     1.24.3          py310hb93e574_0  
numpy-base                1.24.3          py310haf87e8b_0  
omegaconf                 2.3.0                    pypi_0    pypi
openssl                   3.0.8                h1a28f6b_0  
packaging                 23.1                     pypi_0    pypi
pandas                    1.5.3           py310h46d7db6_0  
pathspec                  0.11.1                   pypi_0    pypi
pillow                    9.4.0           py310h313beb8_0  
pip                       23.1.2          py310hca03da5_0  
platformdirs              3.6.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.0.0          py310hca03da5_0  
pysocks                   1.7.1           py310hca03da5_0  
python                    3.10.11              hb885b13_3  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pytorch                   2.0.1                  py3.10_0    pytorch
pytz                      2022.7          py310hca03da5_0  
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h1a28f6b_0  
requests                  2.29.0          py310hca03da5_0  
setuptools                67.8.0          py310hca03da5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h80987f9_0  
sympy                     1.11.1          py310hca03da5_0  
tk                        8.6.12               hb8d0fd4_0  
tomli                     2.0.1           py310hca03da5_0  
torchaudio                2.0.2                 py310_cpu    pytorch
torchvision               0.13.1          cpu_py310he5d19f7_0  
tqdm                      4.65.0          py310h33ce5c2_0  
typing_extensions         4.6.3           py310hca03da5_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.16         py310hca03da5_0  
wheel                     0.38.4          py310hca03da5_0  
xz                        5.4.2                h80987f9_0  
zlib                      1.2.13               h5a0b063_0  
zstd                      1.5.5                hd90d995_0  
