units:
  endtime_s: [hr]
  forcing_resolution_h: [sec]
  timestep_h: [s]
constants:
  frozen_factor: 1
  AET_thresh_Theta: 0.85  # scaled soil moisture (0-1) above which AET=PET (fix later!)
  AET_expon: 1.0
  nint: 120
conversions:
  cm_to_mm: 10.0
  mm_to_cm: 0.1
  cm_to_m: 0.01
  hr_to_sec: 3600.0
  m_to_cm: 100.0
local_rank: ???
nproc: ???
distributed_backend: "gloo"  # CPU
#distributed_backend: "nccl"  # GPU