data_dir: {$cwd}
# Setting the dataset and information related:
dataset: Phillipsburg
soil_state: c_soil
batch_size: 1
forcing_file: ${cwd}/flat_files/LGAR-C-tests/forcing_data_resampled_uniform_Phillipsburg.csv
soil_params_file: ${cwd}/flat_files/vG_default_params.dat
observations_file: ${cwd}/flat_files/usgs_streamflow/${basin_id}-usgs-hourly.csv
subcycle_length: 3600.0 #[sec]
forcing_resolution: 3600 # [sec]
endtime: 372.0 #[hr]
layer_thickness: #[cm]
  - 44.0
  - 131.0
  - 25.0
initial_psi: 2000.0 #[cm]
ponded_depth_max: 2 #[cm]
use_closed_form_G: False
layer_soil_type:
  - 12
  - 13
  - 14
num_soil_layers: 3
wilting_point_psi_cm: 154950.0  # AJ-correction
soil_parameter_index: ???
wilting_point_psi: 15495.0 #[cm]
giuh_ordinates:
  - 0.06
  - 0.51
  - 0.28
  - 0.12
  - 0.03

