units:
  endtime_s: [hr]
  forcing_resolution_h: [ sec ]
  timestep_h: [s]
subcycle_length: 3600 #[sec]
subcycle_length_h: ??? #[hr]
num_subcycles: ???
#num_time_step: 90000  # total simulation time is this number times the time_step_s
endtime: 3000.0 #[hr]
endtime_s: ???
forcing_resolution_h: ???
time_per_step: ???
nsteps: ???
forcing_resolution: 3600 # [sec]
hyperparameters:
  warmup: 168
  epochs: 50
  learning_rate: 0.001
  minibatch: 15 # [days]
#  minibatch: 1/24 # this makes no minibatch
  lb:
    - 0.0015 # alpha
    - 1.0 # n
    - 1e-6 # Ksat
    - 0.001 # ponded_depth_max
  ub:
    - 0.015 # alpha
    - 5.0 # n
    - 30 # Ksat
    - 10.0 # ponded_depth_max
  # https://www.pc-progress.com/Downloads/Public_Lib_H1D/HYDRUS-1D_Tutorial_V1.00_2018.pdf
  # https://acsess.onlinelibrary.wiley.com/doi/pdf/10.2136/sssaj1980.03615995004400050002x
