import hydra
import logging
from omegaconf import DictConfig
import os
import time

from dpLGAR.agents.DataParallelLGAR import DataParallelLGAR
from dpLGAR.agents.SingleBasinRun import LGARAgent
from dpLGAR.agents.SyntheticAgent import SyntheticAgent

from pathlib import Path

cwd = Path.cwd()
log = logging.getLogger(__name__)


@hydra.main(version_base=None, config_path=".", config_name="config")
def main(cfg: DictConfig) -> None:
    cfg.cwd = cwd
    start = time.perf_counter()
    try:
        # Running the code in Parallel
        # Pulling the LOCAL_RANK that is generated by torchrun
        cfg.local_rank = int(os.environ["LOCAL_RANK"])
        agent = DataParallelLGAR(cfg)
    except KeyError:
        # There is no Data Parallel in use
        cfg.local_rank = 0
        cfg.nproc = 1
        if cfg.synthetic.eval:
            agent = SyntheticAgent(cfg)
        else:
            agent = LGARAgent(cfg)

    agent.run()
    agent.finalize()
    end = time.perf_counter()
    log.debug(f"Run took : {(end - start):.6f} seconds")


if __name__ == "__main__":
    main()
