defaults:
  - _self_
  - datazoo: config/Phillipsburg
  - modelzoo: config/shorter_subcycle
  - datautils: config/base
  - override hydra/launcher: joblib

#cwd: /mnt/sdb1/tkb5476/dpLGAR/
cwd: /Users/taddbindas/projects/dpLGAR

# Model information
mode: train
basin_id: "06332515"

save_name: ${basin_id}_train
output_dir: ${cwd}/output
device: cpu
print_output: False # Not supported rn
save_paths:
#  precip: ${cwd}/flat_files/save_files/precip.csv
  precip: ${cwd}/flat_files/save_files/test.csv
  pet: ${cwd}/flat_files/save_files/PET.csv
  soil_moisture: ${cwd}/flat_files/save_files/soil_moisture.csv
  soil_thickness: ${cwd}/flat_files/save_files/soil_thickness.csv
synthetic:
  eval: False
  run: True
  output_dir: ${cwd}/runs/synthetic/
  name: ${basin_id}_${flat_files.time_interval.warmup}-${flat_files.time_interval.end}.csv

################## HYDRA CONFIG #######################
hydra:
  help:
    app_name: differentiable parameter Learning LGAR (dpLGAR)
    header: == ${hydra.help.app_name} ==
    template: |-
      ${hydra.help.header}

      This is ${hydra.help.app_name}!
      Work in progress

      ${hydra.help.footer}
    footer: |-
      Powered by Hydra (https://hydra.cc)
      Use --hydra-help to view Hydra specific help
  job:
    name: ${save_name}
  run:
    dir: ${cwd}/output/${now:%Y-%m-%d}_${hydra.job.name}/${now:%H-%M-%S}