defaults:
  - _self_
  - data: basin_06332515
  - models: mlp
  #  - models: config/shorter_subcycle
  - hydra_settings: settings
#cwd: /mnt/sdb1/tkb5476/LGAR-py/
cwd: /Users/taddbindas/projects/soils_work/lgar-py/
seed: 0
save_name: debugger
output_dir: ${cwd}/output
device: cpu
print_output: False # Not supported rn
save_paths:
#  precip: ${cwd}/data/save_files/precip.csv
  precip: ${cwd}/data/save_files/test.csv
  pet: ${cwd}/data/save_files/PET.csv
  soil_moisture: ${cwd}/data/save_files/soil_moisture.csv
  soil_thickness: ${cwd}/data/save_files/soil_thickness.csv
constants:
  frozen_factor: 1
  AET_thresh_Theta: 0.85  # scaled soil moisture (0-1) above which AET=PET (fix later!)
  AET_expon: 1.0
  nint: 120
conversions:
  cm_to_mm: 10.0
  mm_to_cm: 0.1
  cm_to_m: 0.01
  hr_to_sec: 3600.0