defaults:
  - _self_
  - data: config/Phillisburg
cwd: /Users/taddbindas/projects/LGAR-Torch
save_name: debugger
output_dir: ${cwd}/ouutput
initializations:
  num_soil_types: 15  # must be less than or equal to MAX_NUM_SOIL_TYPES
  num_soil_layers: 3  # must be less than or equal to MAX_NUM_SOIL_LAYERS
  num_fronts: 0  # must be less than MAX_NUM_FRONTS
  root_zone_bottom_layer: 2  # example, iff set to 2, then the root zone is in layer 1 and 2

################## HYDRA CONFIG #######################
hydra:
  help:
    app_name: LGAR-TORCH
    header: == ${hydra.help.app_name} ==
    template: |-
      ${hydra.help.header}

      This is ${hydra.help.app_name}!
      Work in progress

      ${hydra.help.footer}
    footer: |-
      Powered by Hydra (https://hydra.cc)
      Use --hydra-help to view Hydra specific help
  job:
    name: ${save_name}
  run:
    dir: /mnt/sdb1/Database/SI2023/output/${now:%Y-%m-%d}_${hydra.job.name}/${now:%H-%M-%S}